### ISSUE TITLE
Keep alive all db connection 

### ISSUE THREAD

**Issue by kapilasr** [gwinstanley/DBPool#5]
Dear ALL,

I'm using DBPool-5.0.jar in my transaction server. But I'm facing a situation where connection timeout from database server after 8 hours.
Let me know how to PING / Keep Alive all connection in pool periodically  ?

Java version 1.6  on 64 bit.
Os - RHEL 5.4 on 64 bit.

Database 

| version                                   | 5.0.77                                                     
| version_bdb                           | Sleepycat Software: Berkeley DB 4.1.24: (January 29, 2009) 
| version_comment                  | Source distribution                                        
| version_compile_machine     | x86_64                                                     
| version_compile_os               | redhat-linux-gnu                                           
| wait_timeout                           | 28800                                                      

Much appreciate your expert on this matter.

Regards

**Comment by gwinstanley** [comment]
As the [DBPool documentation](http://www.snaq.net/java/DBPool/) explains, you can use the idleTimeout pool property (specified in seconds) to ensure connections are not left idle for too long. In case this is not enough, you can also add more rigorous connection checking using a connection validator. Again, see the documentation for an explanation of how to use this feature.

**Comment by kapilasr** [comment]
Thanks for the reply and already went through the doc but one more clarification yet 

-idleTimeout    is the pooled idle timeout  but in my cause it's taking place from db server. 
-Validator         is only checking the connection while it's taking from the pool.   If the connection status is failed, there is no way to continue the incoming transaction. 

What I required to keep alive  all active  connections only in pool (set idleTimeout=0 means no need to expire at application level ). So before expiring the connection from database side, I need to have  execute test cycle for all connections in pool whether it's using or not long time by app.

I have seen some different pool application is using parameter like "validationInterval"  Is there something like that ?

Regards

**Comment by gwinstanley** [comment]
I believe *idleTimeout* is the one you want; the idle time for connections is monitored, and when this threshold is exceeded for a pooled connection, it is closed. If this and connection validation together are insufficient, for example if database requests are infrequent enough that new connections do not fill the pool again after *idleTimeout* is reached, then you can use *minPool* to repopulate the pool after *idleTimeout* has caused connections to be closed. There is no validationInterval property as you suggest, no. I believe a suitable configuration of idleTimeout/minPool & connection validation should solve your problems. If not, then you need to look more into Berkeley DB server configuration to see how you can mitigate the issue. Eight hours has been the standard for MySQL typically also, and these mechanisms can be successfully used to work around that limit.

**Comment by kapilasr** [comment]
Thanks for quick reply 

Let me know how connection validation is exactly  working ? 

Example, 
If validation is failing, will it try to borrow another connection in pool?


Repopulating the pool, will you recommend ? 


-idleTimeout - Will it only work for demand connection ? means MIN pool connections are still available in pool ? 

From doc  (at least one open connection available)

"Note that comments are allowed, as it's a standard Java properties file. To save resources and to avoid compromising performance a maximum of 10 connections are pooled for re-use. When demand is high up to 30 connections may be handed out, and when demand is low, each connection will expire after ten minutes of idle time (600 seconds). When there is no demand there should also always be at least one open connection available."



And small clarifcation on application level 
Should method or pool object  be synchronized ? 

public static synchronized Connection getConnection()throws Exception{
		Connection con = pool.getConnection(5000);
		
		return con;
	}

Regards

**Comment by gwinstanley** [comment]
If validation fails when a connection is retrieved from the pool, that connection is destroyed, then another connection is selected from the pool (if available). If there are none available, and the pooling parameters permit, another is created for use, otherwise, ```null``` is returned.

*idleTimeout* works for all pooled connections. If this threshold is reached for a connection, it is destroyed and another created if *minPool* specifies a minimum number of pooled connections. If *minPool* connections are still available after timeout, another is not created.

For multithreaded use, DBPool is internally thread-safe, so you can retrieve/close connections from multiple different threads safely without additional locks. So, your use of ```synchronized``` in this case should be unnecessary.

Hope that helps.

**Comment by kapilasr** [comment]
Really much thanks for all given information !

Let me know how basically connection is invalid in pool ? (For my understanding )

Regarding idleTimeout,  I can see  that it's destroyed once threshold is reached. but minPool population will not happen there. Is there any reason ?

minPool = 5 , idleTimeout = 10


Apr 23, 2015 7:51:55 AM snaq.util.ObjectPool log_info
INFO: MYSQL: Getting connection (user/password): jdbc:mysql://192.168.1.241:3306/epictle
Apr 23, 2015 7:51:55 AM snaq.util.ObjectPool log_info
INFO: MYSQL: Created a new connection
Apr 23, 2015 7:51:55 AM snaq.util.ObjectPool log_info
INFO: MYSQL: Getting connection (user/password): jdbc:mysql://192.168.1.241:3306/epictle
Apr 23, 2015 7:51:55 AM snaq.util.ObjectPool log_info
INFO: MYSQL: Created a new connection
Apr 23, 2015 7:51:55 AM snaq.util.ObjectPool log_info
INFO: MYSQL: Getting connection (user/password): jdbc:mysql://192.168.1.241:3306/epictle
Apr 23, 2015 7:51:55 AM snaq.util.ObjectPool log_info
INFO: MYSQL: Created a new connection
Apr 23, 2015 7:51:55 AM snaq.util.ObjectPool log_info
INFO: MYSQL: Getting connection (user/password): jdbc:mysql://192.168.1.241:3306/epictle
Apr 23, 2015 7:51:55 AM snaq.util.ObjectPool log_info
INFO: MYSQL: Created a new connection
Apr 23, 2015 7:51:55 AM snaq.util.ObjectPool log_info
INFO: MYSQL: Getting connection (user/password): jdbc:mysql://192.168.1.241:3306/epictle
Apr 23, 2015 7:51:55 AM snaq.util.ObjectPool log_info
INFO: MYSQL: Created a new connection
Apr 23, 2015 7:52:10 AM snaq.util.ObjectPool log_info
INFO: MYSQL: Destroyed connection
Apr 23, 2015 7:52:13 AM snaq.util.ObjectPool log_info
INFO: MYSQL: Destroyed connection
Apr 23, 2015 7:52:13 AM snaq.util.ObjectPool log_info
INFO: MYSQL: Destroyed connection
Apr 23, 2015 7:52:13 AM snaq.util.ObjectPool log_info
INFO: MYSQL: Destroyed connection
Apr 23, 2015 7:52:13 AM snaq.util.ObjectPool log_info
INFO: MYSQL: Destroyed connection

Regards,

**Comment by gwinstanley** [comment]
The source code is your friend: [ConnectionPool.java](https://github.com/gwinstanley/DBPool/blob/master/src/main/java/snaq/db/ConnectionPool.java) (search for ```isValid```). The default implementation simply checks if ```Connection.isClosed()``` has been called, but this can easily be changed by specifying a ```ConnectionValidator``` instance to the pool &/ manager. All of these questions can be answered by examining the source code, and may help you understand the process by which things are happening.

Regarding connection destruction/recreation via *minPool*, it is really intended for pool size maintenance during periods of low connection use, in preparation for bursts of demand. For handle this, the creation is managed by a separate thread which monitors the pool, so may occur at a slightly different time. Similarly the destruction of timed out connections happens on a separate thread, so these processes are not necessary simultaneous or time-adjacent.

**Comment by kapilasr** [comment]
Thanks for your kind support on this matter.  really great place here for developers like me

**Comment by gwinstanley** [comment]
You're welcome, and I hope it's resolved your issue.
