### ISSUE TITLE
getConnection Method gets slow 

### ISSUE THREAD

**Issue by kapilasr** [gwinstanley/DBPool#6]
Dear Sir, 

I'm using DBPool-5.0.jar in my transaction server. But I'm facing a situation where sometimes taking a connection from pool seems like too delay.

Java version 1.6 on 64 bit.
Os - RHEL 5.4 on 64 bit.

Database Information as bellow 

| version | 5.0.77
| version_bdb | Sleepycat Software: Berkeley DB 4.1.24: (January 29, 2009)
| version_comment | Source distribution
| version_compile_machine | x86_64
| version_compile_os | redhat-linux-gnu
| wait_timeout | 28800 

In my application 

Database configuration as bellow 

Driver - com.mysql.jdbc.Driver
Url - jdbc:mysql://192.168.1.34:3306/livedb
Max pool - 20
Min pool - 10
Max pool size - 60
Idle timeout - 600

	public static  Connection getConnection()throws Exception{
		
		
		Connection con = pool.getConnection(6000);
		if (con !=null)con.setAutoCommit(false);
		return con;
	}

//Taking a connection from pool

long t1 = System.currentTimeMillis();
Connection con = DBconnections.getConnection();	
long t2 = System.currentTimeMillis();

t2-t1  gets sometimes 60 -70 s  (Most of time it's getting pretty value around 1 m)

Should I change some configuration from database side ? 

Appreciate your expert advice to resole this issue. 

Regards

**Comment by gwinstanley** [comment]
A large number of code changes have been implemented since v5.0, so I strongly recommend you upgradeto the latest possible version. That said, I know you're using Java 1.6, which makes this less realistic. If you can handle the changeover from using Apache Common Logging to using SLF4J instead, then I've [pre-compiled a Java 6 version](http://www.snaq.net/java/DBPool/dbpool-7.0-jdk6.jar) for you. If this isn't feasible then let me know, and I'll upload an old copy of v5.1 for you to try.

**Comment by kapilasr** [comment]
Dear Giles,

Thanks a lot for working me !



First let me try with your latest release.

New Environment

-Java

java version "1.7.0_03"
Java(TM) SE Runtime Environment (build 1.7.0_03-b04)
Java HotSpot(TM) 64-Bit Server VM (build 22.1-b02, mixed mode)


-DBPool

Version 7.0 (I think your latest one)


-JDBC driver


Connector/J 5.1.35  (however you have recommended 4.1).  Is there any issue
using latest JDBC driver (5.1.35)? or should I use recommended one as in
your site ?


One more clarification

-Let us know that which method in bellow is most prepared  for creating a
db pool ?  (I'm using a standalone application with only  single database )

-DBPoolDataSource
-ConnectionPool

-I'm just trying to use properties file for (ConnectionPool) making a
connection pool but I have small doubt regarding PoolName

In you example, it's local

name=poolman1
drivers=com.mysql.jdbc.Driver

local.url=jdbc:mysql://10.0.0.7:3306/homeDB
local.user=jason
local.password=Argonaut1
local.maxpool=3
local.maxsize=0
local.idleTimeout=3600


Can it be any name ? if yes, how does program identify exact value for url,
user .... etc ?



Much appreciate your kind support.


Regards,
