### ISSUE TITLE
bug for DBPoolDataSource set minpool size

### ISSUE THREAD

**Issue by weiransoft** [gwinstanley/DBPool#8]
public synchronized void setMinPool(int minPool)
  {
    this.maxPool = minPool;
    if (pool != null)
      pool.setParameters(this.minPool, pool.getMaxPool(), pool.getMaxSize(), pool.getIdleTimeout());
  }

this.maxPool = minPool;
correct is ：
this.minPool = minPool;

**Comment by gwinstanley** [comment]
Thanks for the feedback. I've just fixed this bug, and published v7.0.1 to Maven and main download site.
